version: '3'
services:
  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: process.env.MYSQL_PASSWORD
      MYSQL_DATABASE: process.env.MYSQL_DATABASE_NAME
    ports:
      - "33060:3306"